# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4']

    steps:
    - name: Run Confluent Platform (Confluent Server)
      uses: zendesk/cp-all-in-one-action@v0.2.1
      with:
        service: broker

    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Wait for broker to boot
      run: 'while ! nc -z localhost 9092; do echo -n "."; sleep 0.1; done'

    - name: Run tests
      run: bundle exec rake
      env:
        DELIVERY_BOY_BROKERS: localhost:9092
